all:
  hosts:
    master:
      ansible_host: 192.168.1.19
      ip: 192.168.1.19
      access_ip: 192.168.1.19
    node1:
      ansible_host: 192.168.1.18
      ip: 192.168.1.18
      access_ip: 192.168.1.18
  children:
    kube_control_plane:
      hosts:
        master:
        node1:
    kube_node:
      hosts:
        master:
        node1:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
