{
 "title": "grafana learning",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "period1",
    "label": "period",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "workload",
    "label": "version",
    "query": {
     "query": "query_result(istio_requests_total)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "query_result(container_memory_working_set_bytes)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "query_result(container_memory_working_set_bytes)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "query_result(istio_requests_total)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Response Bytes Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "istio_response_bytes_bucket{app=~\"$app\", destination_workload=~\"$workload\", response_code=\"200\"}",
     "legendFormat": "{{destination_workload}}-{{le}}"
    }
   ]
  },
  {
   "title": "Response Byte Summary",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "istio_response_bytes_sum{app=~\"$app\",destination_workload=~\"$workload\", response_code=\"200\"}",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  { "title": "counter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Request Total Based on version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(istio_requests_total{app=~\"$app\", destination_workload=~\"$workload\",response_code=\"200\"}[$period1])",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Rate of request",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(istio_requests_total{app=~\"$app\", destination_workload=~\"$workload\", response_code=\"200\"}[$period1])",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  { "title": "gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory Usage based on Pods/Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  }
 ]
}